### ISSUE TITLE
Reconnection / Reload on time away from network

### ISSUE THREAD

**Issue by Serubin** [klinker-apps/messenger-web#20]
Conversations and threads should be reloaded after significant time away from a network. Currently the reconnecting websocket will handle if a client disconnects from the web and the websocket loses connection. This is not handled as nicely if a computer goes to sleep. Ideally the client should check the last_ping and reload if it exceeds a certain time limit. 

last_ping is already stored in the local state.

**Comment by rrtigga** [comment]
@klinker24 would you be able to send me a refund given you only display 75 contacts? I sent you an email at Mon, Jun 10, 11:21 AM (21 hours ago). It is under FunkyFreshGuru . <nigatigga@gmail.com> with the subject line "Unable to scroll down to view all conversations - Pulse Web". Just had to re-notify you because you have indicated on your website that you allow 2 days for a refund, so I'll take that. 

Thanks!

**Comment by klinker24** [comment]
@rrtigga That doesn't have anything to do with this issue. I am not sure why you posted it here.

I already told you, yesterday, exactly how you can see all of your conversations on the web: https://github.com/klinker-apps/messenger-web/issues/78#issuecomment-500539786

My refund policy is for if there isn't a solution to your issue. Yours has a simple solution.

https://messenger.klinkerapps.com/overview/pricing.html

**Comment by rrtigga** [comment]
I'm running a texting service for teens to provide mental health support and help them navigate life challenges. I have hundreds of conversations and I'm unable to archive conversations that I can't even see. I was just looking at Pulse SMS as a speedier solution to Google Messages. I read through the information, FAQs, reviews, refund policy and decided to make the lifetime purchased based off the 2-days refund policy. Once I learned that it doesn't display over 75 conversations that made it unusable for me given I have to maintain hundreds of different conservations based off different dates, time zones and follow-up at different times. I'm an honest person. I am not asking anything unreasonable. All I'm asking for is for my $10.99 back since I purchased it less than 24 hours ago. If I knew that it didn't display over 75 conservations, I wouldn't have bought it. You've done yourself a great job with maintaining the app and being a great developer/one-man army and I'm sure you're making a killing of this, but I'm having a significant issue with lack of basic functionality on the web. If I did the 1-month, 3-month, or 1-year, there would no problem because there would be no issue with getting a refund due to 7-day trial. But this situation makes no sense, given that I paid the lifetime and didn't even know that I wouldn't be able to get over 75 conversations and I can't get a refund only because it's lifetime. How was I supposed to know that I wouldn't get 75 conversations? There is nothing on the website or support section to indicate that. And it is a minimum expectations to be able to load all your conversations on web. Plus it's an unfair situation for a certain segment of customers. Customers who do the 1-month, 3-month and 1-year can try it out for 7 days and get their money back no questions asked and are, therefore, able to figure out if they can get over 75 conversations on web; however, if I purchase lifetime and find out I can't get over 75 conversations I am unable to get my money back? I just find this unfair. Would I not be able to get a refund?

**Comment by klinker24** [comment]
In fact, there is a support topic stating exactly what I have told you. 

![Screen Shot 2019-06-11 at 12 39 56 PM](https://user-images.githubusercontent.com/4874287/59294016-176b0600-8c46-11e9-8185-16e722d52776.png)

As I have also said, you can load all of your conversations. Pulse meets the requirement that you have set. You can add these conversations to folders, or archive them, to view the entire history. You are setting this 75 conversation limit, yourself. The app is not limiting you.

This discussion has nothing to do with this issue, I am not sure why you are continuing to comment here. If you have to have a refund, then you would need to provide your order number over email.

**Comment by Serubin** [comment]
Do we still need this issue open - I am under the impression that this is mostly resolved.
