### ISSUE TITLE
CLI for checking and responding?

### ISSUE THREAD

**Issue by InTEGr8or** [klinker-apps/messenger-web#50]
Being able to check and respond to messages from the command line would be a wonderful enhancement.

**Comment by klinker24** [comment]
Is there any reason why you want this? That seems extremely limited to be honest. There are some things that you just need a UI for and a real framework to track state, etc...

Some of the bigger concerns I have:

* How would you manage the authentication? You have to store the encryption credentials somewhere, which rely on the password
* It would be all based on numbers and ids (querying, sending to a conversation, deleting a message). I can't really see that being useful or more than a hassle, for any case?
* What about the real-time aspect of messaging? Popping up messages through the web socket would definitely interrupt what you are typing and get in the way.

I don't think that this is something I would ever create for the app, sorry. The APIs, encryption, and requirements are all here though, in this repo, so anyone could really make a CLI for Pulse. It just seems like it would be very under-utilized and not nearly as useful as the web and desktop apps. 

If you just want this because you are a keyboard person, Pulse has some shortcut keys already. I would be more than willing to accept any PRs to expand on this functionality. I do not see myself making a CLI for the app though, sorry.

https://github.com/klinker-apps/messenger-web/blob/master/src/utils/shortcuts.js
https://messenger.klinkerapps.com/help
