### ISSUE TITLE
Material 2 UI

### ISSUE THREAD

**Issue by Serubin** [klinker-apps/messenger-web#52]
I've been playing around with some Material 2 UI design components. Here's a simple mockup to discuss. This shows the rounded sidebar, 3-dot menu, and new fab menu as examples.
<img width="989" alt="screen shot 2018-08-31 at 12 21 09 am" src="https://user-images.githubusercontent.com/1234465/44892641-e2dc1e00-acb3-11e8-8323-f28c662f9d38.png">

**Comment by Serubin** [comment]
Made some updates - not super pleased with this gap - but given that the sidebar moves it may just be how it stays.
<img width="262" alt="screen shot 2018-08-31 at 3 51 38 pm" src="https://user-images.githubusercontent.com/1234465/44933109-eb753880-ad35-11e8-8126-9bf3d837222a.png">
<img width="283" alt="screen shot 2018-08-31 at 3 52 00 pm" src="https://user-images.githubusercontent.com/1234465/44933111-ef08bf80-ad35-11e8-8a7a-ea7eb8312095.png">

**Comment by klinker24** [comment]
Nice, I like it. I made just a few small changes:

* more padding on the left side of the icon
* a very slight rounding to the corners on the left side, since everything else has slightly rounded corners
<img width="274" alt="screen shot 2018-08-31 at 3 14 18 pm" src="https://user-images.githubusercontent.com/4874287/44933919-8ec34f00-ad30-11e8-9472-07561a83d74b.png">

**Comment by Serubin** [comment]
That looks perfect. That polished it very well!

**Comment by klinker24** [comment]
I made a comment on this commit, about the shadows, if you want to take a look: https://github.com/klinker-apps/messenger-web/commit/63f58a7b90fab8fda1fa74621e9ad39f7ffb1f69

I also wanted to test out a bit more of a distinction between the active item and the other ones. I know you said yesterday you were a fan of less shadows, but since they are already on the conversation items, what do you think of this one?

With shadow:
<img width="973" alt="screen shot 2018-09-01 at 10 12 43 am" src="https://user-images.githubusercontent.com/4874287/44947339-6dff0600-add1-11e8-815e-89d77505cfff.png">

Without shadow:
<img width="962" alt="screen shot 2018-09-01 at 10 13 04 am" src="https://user-images.githubusercontent.com/4874287/44947342-75261400-add1-11e8-981a-7c04dba69348.png">

I think that the shadow should be tweaked to match the `ConversationItem` shadows, as well. Wanted to get your opinion on that, from my commit comment, though

**Comment by Serubin** [comment]
Just for archival purposes, this is what the current shadows on the conversation cards look like.

![image](https://user-images.githubusercontent.com/1234465/45452943-59fab480-b6ad-11e8-979f-c99226e4e5a5.png)
