### ISSUE TITLE
Color Picker for Web UI

### ISSUE THREAD

**Issue by tanelso2** [klinker-apps/messenger-web#92]
The web ui should have a better color picker than just entering hex values.

Example:
![image](https://user-images.githubusercontent.com/4315820/65111235-10176f00-d990-11e9-8bdb-c6d26011934b.png)

I'm perfectly okay with doing the research and the implementation for this, if you don't have the time. Mainly I'm just writing this down to remember my idea.

**Comment by Serubin** [comment]
Since much of these changes can be done on the phone, we felt this wasn't a priority feature. On top of that, finding a good color picker that is both usable, modern, and fits our design standard is difficult. 

With that said, we'd love to see contributions regarding this or if you have a library in mind we can collaborate to make this happen. In either case, we're open to helping where we can.

**Comment by klinker24** [comment]
This is actually something that has been requested and tracked over here: https://github.com/klinker-apps/messenger-issues/issues/749

We are more than willing to accept contributions towards any web functionality. 

I am going to close out this issue though, so that this is only open in one place.

**Comment by tanelso2** [comment]
@Serubin - a quick google search led me to this library: https://github.com/Simonwep/pickr

Looks pretty good to me, but obviously y'all would know better if it fits in with your design standard.

**Comment by Serubin** [comment]
That looks good to me

**Comment by Serubin** [comment]
@tanelso2 Did you get a chance to play around at all? Need any help with contributing? 

Reopening for task tracking

**Comment by tanelso2** [comment]
Hey @Serubin - Nah I haven't had a chance yet. I've been sick for about a week now and haven't really done anything productive lately 😷
